version: "3.9"

services:
  brain:
    build: .
    image: brain_function_visualisation:latest
    environment:
      - PYTHONUNBUFFERED=1
    stdin_open: true
    tty: true
    command: ["python", "main.py", "What happens in the brain during a math calculation?"]
